// export enum MovieGenres {
//     Drama = "Drama", 
//     Thriller = "Thriller", 
//     Comedy = "Comedy", 
//     Action = "Action", 
//     Horror = "Horror", 
//     Adventure = "Action", 
//     Musical = "Musical", 
//     Noir = "Noir", 
//     Romance = "Romance", 
//     RoadMovie = "RoadMovie",
//     Experimental = "Experimental", 
//     WuXiaPian = "WuXiaPian",
//     Chanbara = "Chanbara",
//     Western = "Western", 
//     SciFi = "SciFi", 
//     Biopic = "Biopic", 
//     Mystery = "Mystery", 
//     Sport = "Sport", 
//     War = "War", 
//     Giallo = "Giallo", 
//     Historical = "Historical", 
//     Blockbuster = "Blockbuster",
//     Other = "Other",
// }

export enum MovieGenres {
    Drama ,
    Thriller,
    Comedy ,
    Action,
    Horror,
    Adventure,
    Musical,
    Noir,
    Romance,
    RoadMovie ,
    Experimental ,
    WuXiaPian,
    Chanbara ,
    Western,
    SciFi ,
    Biopic ,
    Mystery ,
    Sport , 
    War ,
    Giallo ,
    Historical ,
    Blockbuster ,
    Polar , 
    Fantasy , 
    Family , 
    Documentary, 
    Other
}